### PR TITLE
this should work for lineofsightto 

### PR DESCRIPTION
**Pull request by Milxnor**
im not sure if this works as i dont make hacks & GetWeaponStats might be able to also be found idk like GetWeaponStatsRow and I also fixed a include error

### CODE REVIEW

**Comment by Visual9999** [comment]
i keep this open and may add it in future....

**Comment by cambo32** [comment]
> im not sure if this works as i dont make hacks & GetWeaponStats might be able to also be found idk like GetWeaponStatsRow and I also fixed a include error

can you please help me with these cheats issues ?
first one 
VS
VS2
second one 
VS3
VS4
third one 
VS5
VS6

**Comment by cambo32** [comment]
Can you please update the offsets ?

**Comment by Visual9999** [comment]
this wont work
pull request denied

**Pull request closed without merging**
